### ISSUE TITLE
results of empty string 

### ISSUE THREAD

**Issue by Heathercoraje** [facn2/PHS#18]
It seems like the array before filtered has items that are just empty strings.

**Comment by mattlub** [comment]
![screen shot 2017-07-27 at 10 22 15](https://user-images.githubusercontent.com/16781318/28658788-923f15ee-72b5-11e7-99d5-9b4c8ef53c70.png)

**Comment by mattlub** [comment]
duplicate of #10

**Comment by Heathercoraje** [comment]
fine
