### ISSUE TITLE
Use of ES6 in front end javascript

### ISSUE THREAD

**Issue by ZooeyMiller** [facn2/PHS#22]
You are using [template literals and arrow functions](https://github.com/facn2/PHS/blob/master/public/script.js#L31-L36) in your front end javascript (in the callback to the `eventListener` attached to the `.inputSearchForm`. We've communicated already that you are expected to write ES5 in the front end, but are free to use ES6 in the back end. This is in the interest of browser compatibility.

**Comment by mattlub** [comment]
#15 !

**Comment by ZooeyMiller** [comment]
@mattlub oops :flushed: closing.
